/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Moonway studios 3d (https://sketchfab.com/moonway3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-apple-imac-with-magic-keyboard-340194d2c370464c9dc240252b1f2ce2
Title: (FREE) Apple Imac with magic keyboard
*/

import { useRef } from 'react';
import { useGLTF, useVideoTexture } from '@react-three/drei';
import * as THREE from 'three';
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';

const IMacComputer = (props) => {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/imac_computer.glb');

  const options = {
    // unsuspend: "canplay",
    crossOrigin: 'Anonymous',
    muted: true,
    loop: true,
    playsInline: true,
  };

  const txt = useVideoTexture(
    props.texture ? props.texture : '/textures/project/intermarche_project.mp4',
    options,
  );

  useGSAP(() => {
    gsap.from(group.current.rotation, {
      y: Math.PI / 2,
      duration: 1,
      ease: 'power3.out',
    });
  }, [txt]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.3}
          position={[0, 1.5, 0]}>
          <group
            name="36c4387b55c2438bab3b403c5ed8a576fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="imac_stand"
                  position={[52.831, -129.173, -45.922]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="imac_stand_base_color_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.imac_stand_base_color_0.geometry}
                    material={materials.base_color}
                  />
                  <mesh
                    name="imac_stand_metal_color_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.imac_stand_metal_color_0.geometry}
                    material={materials.metal_color}
                  />
                  <group name="imac" position={[-0.713, -0.345, 0.804]}>
                    <mesh
                      name="imac_base_color_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.imac_base_color_0.geometry}
                      material={materials.base_color}
                    />
                    <mesh
                      name="imac_screen_white_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.imac_screen_white_0.geometry}
                      material={materials.screen_white}
                    />
                    <mesh
                      name="imac_screen_image_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.imac_screen_image_0.geometry}
                      material={materials.screen_image}>
                      <meshBasicMaterial
                        map={txt}
                        toneMapped={false}
                        side={THREE.DoubleSide}
                      />
                    </mesh>
                    <mesh
                      name="imac_metal_color_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.imac_metal_color_0.geometry}
                      material={materials.metal_color}
                    />
                    <mesh
                      name="imac_black_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.imac_black_0.geometry}
                      material={materials.black}
                    />
                  </group>
                </group>
                <group
                  name="Plane"
                  position={[6.404, -182.76, 360.928]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[250.813, 109.566, 109.566]}>
                  <mesh
                    name="Plane_dene��e_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Plane_dene��e_0'].geometry}
                    material={materials.denee}
                  />
                </group>
                <group
                  name="key"
                  position={[10.095, -169.596, 355.015]}
                  rotation={[-1.51, 0, 0]}
                  scale={[250.813, 109.566, 109.566]}>
                  <mesh
                    name="key_key_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.key_key_0.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload('/models/imac_computer.glb');

export default IMacComputer;
